### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MrAshWasTaken** [Moka-admin0/Np-4.0_MiniGames#1]
How do I see each minigame in browser ?
Opened localhost:3000 but nothing is showing. Is there anyway I can preview each minigame ?
Thanks.

**Comment by Moka-admin0** [comment]
hello "its-heshi" thx for using our minigames,

in order to display each minigames you can go a head to [active minigames lib/store](https://github.com/Moka-admin0/Np-4.0_MiniGames/blob/a8708e626a5f7056c907d6f5d3debe9e624aa3ec/src/lib/store.tsx#L8)

and change the string active value to any minigames name that includes in our minigames, as example : `active: "lockpicking"`

**Comment by MrAshWasTaken** [comment]
Hey [Moka-admin0](https://github.com/Moka-admin0),

Thanks for the quick response and the help. Really appreciate it.

By the way, great work on the minigames pack.
